server:
  port: 8081

mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.unicom.dao

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud?useUnicode=true&characterEncoding=utf-8
    username: root
    password: password
  application:
    name: service-user
eureka:
  client:
    service-url:
      defaultZone: http://${register.hostname}:${register.port}/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
register:
  hostname: 127.0.0.1
  port: 8761


unicom:
  server:
    name: testuserserver